### ISSUE TITLE
17388 - Install and configure Puppet to manage your server -  Ubuntu

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#170]

**Comment by advaiya-main** [comment]
Edited

**Comment by advaiya-main** [comment]
taking back to check html validation issues

**Comment by advaiya-main** [comment]
Edited as per 17389 and corrected the html coding.

**Comment by CrystalSmithwick** [comment]
Should this line be Ubuntu, not Fedora?  line 94 <li>Server with Fedora 20 installed that will act as the master server.</li>

**Comment by CrystalSmithwick** [comment]
Proofed.  Tester - some comments in line regarding distros.  May just be copying errors. Changed all to Ubuntu.

**Comment by advaiya-main** [comment]
Validated testing

**Comment by brianmiller17** [comment]
1) There is no mention of Apache being installed until halfway through the document.  Please revise to either include steps for installing Apache, or include the Apache install as a prerequisite and link this article to an Apache installation article.   
2) "Puppets are of two types:
Puppet Enterprise
Open-source Puppet"

Based on the statement above, I would expect there to be some steps to install Puppet Enterprise and some other steps to install Open-source Puppet OR a statement like " this article is limited in scope to Open-source Puppet.

3)  This is a complex article yet there are zero!!! links to subordinate topics.  You could skip the section on NTP and link to an NTP article.

4) Definitely need a link to setting up private Network DNS.

5) Do all the servers in the network have to be Ubuntu?

**Comment by advaiya-main** [comment]
@gnakan: Hi Gary, do we have any article on NTP and setting up a private network DNS? We searched in the article list and found "17394- Choosing the right DNS configuration - ALL DISTROS" but this article is not yet written. Please suggest.
