### ISSUE TITLE
17391 - Install and configure Puppet to manage your server - Arch Linux

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#173]

**Comment by advaiya-main** [comment]
@gnakan: There is no official package for Arch Linux on Puppet. Please advise.

**Comment by garynakanelua** [comment]
@advaiya-main : Looks like it will need to be installed from source (https://docs.puppetlabs.com/guides/install_puppet/install_tarball.html). In the instructions, you can just wget the tar file, unzip, then run the installation.
