### ISSUE TITLE
17392 - Install and configure Puppet to manage your server - Debian

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#174]

**Comment by advaiya-main** [comment]
Edited 17392 as per the edited version of 17389.

**Comment by advaiya-main** [comment]
Validated testing

**Comment by brianmiller17** [comment]
1) The article assumes an Apache web server without calling this out at the top of the doc.

2) "Puppets are of two types:

Puppet Enterprise

Open-source Puppet"

Based on the statement above, I would expect there to be some steps to install Puppet Enterprise and some other steps to install Open-source Puppet OR a statement like " this article is limited in scope to Open-source Puppet.

3)  This is a complex article yet there are zero!!! links to subordinate topics.  You could skip the section on NTP and link to an NTP article.  
4) Definitely need a link to setting up private Network DNS.

5) Do all the servers in the network have to be Debian?

**Comment by advaiya-main** [comment]
@gnakan: Hi Gary, do we have any article on NTP and setting up a private network DNS? We searched in the article list and found "17394- Choosing the right DNS configuration - ALL DISTROS" but this article is not yet written. Please suggest.
