### ISSUE TITLE
18344 - Configure Themes and Settings for Ghost - Arch Linux

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#21]

**Comment by pmouli** [comment]
First command fails.  Spun a new archlinux server to get this article tested as there was no pre-req specified. - Prabhu

**Comment by advaiya-main** [comment]
Re-edited.

**Comment by Carla-Johnson** [comment]
Edited again. Sending on to testing again.

**Comment by pmouli** [comment]
Dependency article fails (18134)


[prabhu@ArchLinux ~]$ sudo pacman -S base- devel
error: target not found: base-
error: target not found: devel

**Comment by advaiya-main** [comment]
@gnakan: We tried to re-test the dependency article 18134, and still facing the same issue. Same code that worked earlier is now failing. Command failing: cd /var/www/ghost && sudo npm install –production. Also tried the steps from https://wiki.archlinux.org/index.php/Ghost Still getting the same error for the step "npm install --production" (tried with sudo). Please suggest.
