### ISSUE TITLE
17378 - Install an SSL certificate on your web server via SSH - Ubuntu, Debian

### ISSUE THREAD

**Issue by Darrinlange** [gnakan/gd-cloud-docs#213]

**Comment by advaiya-main** [comment]
While attempting to code 17378 article, we found that the html code already exists. Someone else has already written the code for this article. Please suggest.

**Comment by gnakan** [comment]
@advaiya-main Looking at this commit - https://github.com/gnakan/gd-cloud-docs/commit/7f70ef439c5d12d512c77537c19764239c5561fc#diff-126f11d6b312b6c63e29a4c9b3103829, it appears that you all added the article code.

**Comment by advaiya-main** [comment]
Please advise if there is any action item for us.

**Comment by advaiya-main** [comment]
@gnakan : This article is wrongly assigned to us as someone else has already written the code for this in gd-cloud-docs. Please suggest.

**Comment by gnakan** [comment]
@pnadube : Can you take a look at this article. I know you've done SSL cert installs for apache. Does this look familiar?

**Comment by pnadube** [comment]
@gnakan : No, this isn't my article either. I wrote the Install SSL on Apache series.

**Comment by pnadube** [comment]
Closed by mistake

**Comment by kharise** [comment]
Started to test this - really incomplete. It needs prereqs added, including LEMP/LAMP stack, create CRT, etc. Perhaps this should be forked by apache or nginx
