### ISSUE TITLE
18409 - Back up your server with Bacula - Ubuntu, Debian

### ISSUE THREAD

**Issue by Darrinlange** [gnakan/gd-cloud-docs#217]

**Comment by advaiya-main** [comment]
Edited

**Comment by Carla-Johnson** [comment]
This article jumps around and is difficult to follow. Please revise. Thank you.

**Comment by advaiya-main** [comment]
gnakan: This article is a complicated one and we are facing issue in establishing a connection  the between server and the client machine.
