### ISSUE TITLE
18410 - Back up your server with Bacula - CentOS, Fedora

### ISSUE THREAD

**Issue by Darrinlange** [gnakan/gd-cloud-docs#218]

**Comment by advaiya-main** [comment]
We are facing issue in the configuration section and while taking backup from another machine.

•	At times Bacula director service is not running.
•	Verification issues from both side.
•	TLS issue.
•	Client machine issues.

Bacula is quite complicated protocol to understand and process . We are getting issues of authentication error even if both the machine (Server/Client) has same credentials.
We  also researched in stackoverflow and google but could not find any proper resolution. We have already created new instance and tried twice .
