### ISSUE TITLE
18379 - Install and Configure Ghost via command line - ALL DISTROS

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#22]

**Comment by Carla-Johnson** [comment]
As is, this article needs to be split in 4 (duplicated) for different distros. However, we need to resolve what the subject matter is. The title is "Configuring and maintaining Ghost from the command line" but the content mostly covers "Installing and configuring Ghost from the command line." We do have  other "Installing and configuring Ghost" articles (e.g., 00030), though not from the command line. Need more info about what "Maintaining" means in the title.

**Comment by kharise** [comment]
Making this "Install and Configure Ghost " and will fork "Maintain Ghost"

**Comment by advaiya-main** [comment]
@kharise: You might be already aware, but just for a reminder,  we already have few articles regarding Ghost installation and configuration with Nginx:
-18132 - Install and configure Ghost with NGINX - Ubuntu.html
-18133 - Install and configure Ghost with NGINX - CentOS, Fedora.html
-18134 - Install and configure Ghost with NGINX - Arch Linux.html
-00030 - Install and configure Ghost with NGINX - Debian.html

**Comment by kharise** [comment]
Closing this since it's extraneous
