### ISSUE TITLE
18321 - Serve Multiple Ghost Blogs on One server Using NGINX - Arch Linux

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#237]

**Comment by vishal0soni** [comment]
The reference article from Digital Ocean (provided in Excel sheet) is basically steps for Ubuntu/Debian and are not applicable for Arch Linux. It talks about updating the configuration file /etc/nginx/sites-enabled/ghost, which do not exist in Arch Linux. Instead, in Arch Linux we found a different configuration file /etc/nginx/nginx.conf. We tried updating this file configuration file, but we are not getting the desired results, and got the following error instead.
We are not able to proceed further with this. Please suggest

**Comment by vishal0soni** [comment]
Hey Gary, We are still stuck with this article. Any guidance / hints regarding this would be helpful.

**Comment by garynakanelua** [comment]
@vishal0soni : can you post your nginx config here?

**Comment by advaiya-main** [comment]
Hello Gary,

Here is the configuration file we tried.

Thanks,
Vishal.
