### ISSUE TITLE
18708 - Install and configure a Jabber XMPP server - Arch Linux

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#238]

**Comment by advaiya-main** [comment]
Jabber XMPP server can be installed using three clients -  Bitlee, Prosody and Pidgin as given in the Arch Linux official site. Please suggest which client should be used to install Jabber XMPP on Arch Linux?

**Comment by gnakan** [comment]
@advaiya-main Let's go with Pidgin. It's the one that Digital Ocean uses as an example: https://www.digitalocean.com/community/tutorials/how-to-install-ejabberd-xmpp-server-on-ubuntu

**Comment by advaiya-main** [comment]
@gnakan: We are facing issues  while configuring Jabber. We  tried to install using the pacman repository and it ran successfully but the GUI failed showing 404  error.
Also tried to connect using pidgin client but when pidgin connects to jabber, log shows that “Accepted connection from XXX.xxx.xxx.xxx IP” but pidgin could not be online.
Another method tried that we is install from http://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/14.12/ejabberd-14.12-linux-x86_64-installer.run -o ejabberd-14.12-linux-x86_64-installer.run  link which is an installer of jabber but still facing the same issue. Please suggest.

Reference : 
http://blog.jonhibbard.com/2014/10/installing-nodejs-and-npm-on-centos-6-5/
http://blog.eldajani.net/arch-linux-ejabberd/
https://www.ejabberd.im/node/3598
