### ISSUE TITLE
17843 - Install and configure Apache Subversion (SVN) - Arch Linux

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#241]

**Comment by advaiya-main** [comment]
Re-edited

**Comment by CrystalSmithwick** [comment]
Proofed.

**Comment by advaiya-main** [comment]
validated testing

**Comment by kharise** [comment]
@advaiya-main:
I added a few clarification to vague instructions based on the Arch wiki. Please confirm these are correct.
In "Set up SVN with Apache - Configure Apache and SVN": 
I added this step entirely.
2.Find this line and uncomment it. 
Include conf/extra/httpd-vhosts.conf

For step 7, I added "inside a virtual host directive."
7.Add the following lines inside a virtual host directive: 
In this section "Set up SVN with Apache - Configure Apache and SVN", the last step:
12.Open a browser, and go to http://your_ip_address/svn/test. Successful execution of the above steps will result in the creation of three new directories: trunk, tags, branches. 
I get a prompt for user and pw. 
1) First of all, is that expected? If so, add that into the article so we know to expect it and what to input. 
2) When I enter in "svnuser" and the pw I'd set up, I'm not able to access. Error msg:
Access forbidden!

You don't have permission to access the requested object. It is either read-protected or not readable by the server.

If you think this is a server error, please contact the webmaster.
Error 403
192.169.168.71
Apache/2.4.16 (Unix) SVN/1.9.2

When I tested the article as it stood, when I got to 
12.Open a browser, and go to http://your_ip_address/svn/test., 
I got this error pg:
Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.
Error 404
192.169.168.69
Apache/2.4.16 (Unix) SVN/1.9.2

Please be sure to sync. Fix the article, then send back once you've verified.
thanks!

**Comment by advaiya-main** [comment]
In the Configure Apache and SVN section, when we add the following lines inside a virtual host directive:
<Location /svn>
   DAV svn
   SVNParentPath /home/svn/projects
   AuthzSVNAccessFile /home/svn/.svn-policy-file
   AuthName "SVN Repositories"
   AuthType Basic
   AuthUserFile /etc/svn-auth
   Require valid-user
</Location>

We get error saying "Object not found"

This block of code is taken from the SVN official site from httpd-ssl.conf file. Here is the link: https://wiki.archlinux.org/index.php/Subversion_Setup. Since this official dependency fails, we do not have any other solution. Hence, blocking this article.
