### ISSUE TITLE
19004 - Monitor OSSEC Agents Using an OSSEC Server - Arch Linux

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#242]

**Comment by advaiya-main** [comment]
All other steps are done but could not find help or package to save changes of iptables permanently in Arch Linux. Getting message "perhaps iptables or your kernel needs to be upgraded"​

**Comment by gnakan** [comment]
@advaiya-main Are you using a command like <code>iptables-save > /etc/iptables/iptables.rules</code>

**Comment by gnakan** [comment]
@advaiya-main: Just wanted to make sure you seen my previous comment.

**Comment by advaiya-main** [comment]
@gnakan: We tried this already, but still the same issue.
