### ISSUE TITLE
18574 - Deploy your Rails application with Mina - Arch

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#25]

**Comment by Carla-Johnson** [comment]
This doc has been edited, but needs to be split up into different distros.

**Comment by gnakan** [comment]
You can use 00044, 00045, 00046

**Comment by advaiya-main** [comment]
The articles 00044, 00045 and 00046 are in progress. In this article, we have made few changes while ensuring that previous edits remains the same. Wherever we have changed content, we have added in-line comments to justify.

**Comment by Carla-Johnson** [comment]
This article should now cover only one distribution. 00044, 00045, 00046 were created to cover the other distributions. Please figure out which distribution this article will cover, and delete all the information for the other distributions.

**Comment by advaiya-main** [comment]
Question for Gary:
For the article 18574 - Deploy your Rails application with Mina - ALL DISTROS, we have split the following articles as requested:
•	00044 - Deploy your Rails application with Mina - Debian, Ubuntu
•	00045 - Deploy your Rails application with Mina - CentOS, Fedora
•	00046 - Deploy your Rails application with Mina - Arch Linux

All information we intended to cover is now covered in these three articles. Currently article 18574 is kept as is (having information about all distros). We recommend to discard this article number (18574). Please suggest.

**Comment by gnakan** [comment]
@advaiya-main : lets make 18574 the Arch Linux one and keep 00044 and 00045 as labeled above

**Comment by advaiya-main** [comment]
Renamed 00046 to 18574, so please delete this duplicate ticket
