### ISSUE TITLE
18689 - Install And configure Apache Qpid - Arch Linux

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#256]

**Comment by advaiya-main** [comment]
qpid-tools package is required to install but it is not available for Arch Linux

**Comment by gnakan** [comment]
For now, leave out the installation of that package.

qpid-tools appears to be a sub-package of qpid-cpp. Ran through a large portion of the reference article and everything appears to work correctly.

**Comment by Darrinlange** [comment]
qpid-tools package is required to install but it is not available for Arch Linux. qpid-cpp is also not available. We also tried to install from the scratch. We downloaded the tar.gz but while extracting, linux throws an error of not valid compression. All the .tar.gz are downloaded from the Official site.
