### ISSUE TITLE
18687 - Install and configure Apache Qpid - Ubuntu, Debian

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#258]

**Comment by advaiya-main** [comment]
qpid-tools package is required to install but it is not available for ubuntu.

**Comment by gnakan** [comment]
For now, leave out the installation of that package via apt-get.

qpid-tools appears to be a sub-package of qpid-cpp. Ran through a large portion of the reference article and everything appears to work correctly.

**Comment by advaiya-main** [comment]
qpid-cpp is also not available. We also tried to install from the scratch. We downloaded the tar.gz but while extracting, linux throws an error of not valid compression. All the .tar.gz are downloaded from the Official site.

**Comment by gnakan** [comment]
Appears the package has been removed from the repository: http://www.ubuntuupdates.org/package/core/trusty/universe/base/qpid-tools. Moving to requirements review

**Comment by advaiya-main** [comment]
It worked in Ubuntu, need to check in Debian

**Comment by Carla-Johnson** [comment]
This document has been proofread, but it is too closely copied from the DO article. Please revise using original content and examples.
