### ISSUE TITLE
17365 - Using Git to automate deployment to your server - ALL DISTROS.html

### ISSUE THREAD

**Issue by susankayjordan** [gnakan/gd-cloud-docs#259]

**Comment by garynakanelua** [comment]
@brian-r-miller : The content for this one doesn't match up with the article title. The contents simple cover setting up a git repo on a server. But the necessary steps to enable auto-push to a server on branch merge isn't there.

**Comment by brian-r-miller** [comment]
neither does the DO article.  Do you want me to reaserch and add the auto-push on branch merge?
