### ISSUE TITLE
18536 - Install and configure a social network with Diaspora - Arch Linux

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#272]

**Comment by advaiya-main** [comment]
Edited as per 18535.

**Comment by Carla-Johnson** [comment]
Proofread

**Comment by advaiya-main** [comment]
validated testing

**Comment by brianmiller17** [comment]
Subtending article on installing SSL cert requires web server.  This doc needs a prereq instruction regarding which web server should be used and a link to installing it.

**Comment by advaiya-main** [comment]
Mentioned that we need to use Nginx web server

**Comment by brian-r-miller** [comment]
sudo pacman -U diaspora-mysql-0.5.3.1-1-x86_64.pkg.tar.xz
should be 
 sudo pacman -U diaspora-mysql-0.5.4.0-1-x86_64.pkg.tar.xz
or better yet,  generic name

**Comment by advaiya-main** [comment]
1)In Arch Linux, we cannot use sudo pacman -U diaspora-mysql-0.5.4.0-1-x86_64.pkg.tar.xz as Arch Linux has some limitations and will give error. There we recommend to use sudo pacman -U diaspora-mysql-0.5.3.1-1-x86_64.pkg.tar.xz.

2)After you give sudo mysql_secure_installation command, it will prompt you to enter a password of your choice. Mentioned the same in the article.

**Comment by brian-r-miller** [comment]
I have installed MySQL / Mariadb many times in the course of writing / testing many documents.
 I always use "password" as my password to avoid making mistakes.  If you look at the comment above, you will recognize that it is from the  "sudo mysql_secure_installation" step as noted above.  How can I set the password in this step?

If you are setting the password with an install script you MUST call out what it is to the user or provide instructions for modifying the script.

Try following the steps in the document "as-is" from a clean server and you will see what I mean.

**Comment by brian-r-miller** [comment]
Some more comments:
Specify the Diaspora settings #2 refers to a Postgres DB and 
/etc/webapps/diaspora/database.yml does not exist so a bit difficult to edit it.

Article looks like it was cloned (that's OK) but is sloppy (not OK)
Please write and then test end-to-end using exactly what is written in the doc.
