### ISSUE TITLE
18381 - Automate Ruby On Rails Deployment with Capistrano - CentOS

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#273]

**Comment by advaiya-main** [comment]
Addressed feedback.

**Comment by vishal0soni** [comment]
Taking back to drafting section for second pass.

**Comment by advaiya-main** [comment]
Edited as per guidelines

**Comment by Carla-Johnson** [comment]
Proofread

**Comment by advaiya-main** [comment]
@gnakan: This article works in CentOS but fails in Fedora. In Fedora, script of Nginx services fails. Can you please fork this article into CentOS and Fedora?
