### ISSUE TITLE
17475 - Install Apache Tomcat 6 - CentOS.html

### ISSUE THREAD

**Issue by susankayjordan** [gnakan/gd-cloud-docs#301]

**Comment by brian-r-miller** [comment]
I get a 403 when I try logging in to Tomcat:

HTTP Status 403 - Access to the requested resource has been denied

type Status report

message Access to the requested resource has been denied

description Access to the specified resource (Access to the requested resource has been denied) has been forbidden.

Apache Tomcat/6.0.24

Does Tomcat require a running Apache webserver?  I installed on a virgin machine as per the instructions.
