### ISSUE TITLE
17535 - Install Ruby on Rails using RVM - Fedora

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#360]

**Comment by advaiya-main** [comment]
Edited

**Comment by CrystalSmithwick** [comment]
Edited and ready for review.

$edit-score:A

**Comment by CrystalSmithwick** [comment]
Per GD's Edits there are changes that need to be made.  Please make the edits/changes indicated.  Don't forget to take into account the different distros.

https://docs.google.com/document/d/1ntctzNWdVKh4-kA_KMfKVodUdRdlVDxDB1u3xa92hgI/edit#heading=h.lcaqq7q8zr3m

**Comment by CrystalSmithwick** [comment]
Duplicate with 295.  Please keep 295 if you delete one of these.
