### ISSUE TITLE
18570 - Install CouchDB From Source - Arch Linux

### ISSUE THREAD

**Issue by advaiya-main** [gnakan/gd-cloud-docs#368]

**Comment by advaiya-main** [comment]
Arch Linux package is not available

**Comment by gnakan** [comment]
@advaiya-main :+1: 

Main source is available for download at https://www.apache.org/dyn/closer.lua?path=/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz.

Before installing CouchDB from source, the following packages are required to be installed:

Erlang OTP (>=R12B)
ICU
OpenSSL
Mozilla SpiderMonkey
libcurl
GNU Make
GNU Compiler Collection

These can be installed via the standard package management system.

**Comment by advaiya-main** [comment]
Below is the AUR repository link from where we can download the source,
https://www.archlinux.org/packages/community/x86_64/couchdb/

When we click on "Download from Mirror", we are getting the pre-compiled or ready to install package (couchdb-1.6.1-4-x86_64.pkg.tar.xz).
What we need is that we copy the link location of "Download from Mirror" and 'wget'  in the Arch server. At this point of time we are just getting an index.html page rather than the package (*.tar.gz).

Also please note that we can't download the source file from CouchDB official site and install in Arch Linux, as it won't work at all. For compiling packages in Arch Linux, they need to be first build in a particular source file format and then it is made available in AUR repository for users to download it and compile in server.
You can find the format for source file in,
https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/couchdb

We believe that the issues with downloading the Arch source for Erlang and couchdb from AUR repository is due to the fact that Arch Linux is directly providing both packages through its package manager.
