### ISSUE TITLE
17999 - Deploy a local Django app to your server - Arch Linux 

### ISSUE THREAD

**Issue by susankayjordan** [gnakan/gd-cloud-docs#447]
Creating a new issue,  to track  this article.

**Comment by susankayjordan** [comment]
Article has been re-written

**Comment by Carla-Johnson** [comment]
I started editing this, but the filename and subject matter do not match. Is this doc about installing a LAMP stack or about setting up a Django app? Sending back to coding for now.

**Comment by susankayjordan** [comment]
Verified the content via creator's notes Coded Validated.

**Comment by Carla-Johnson** [comment]
Proofread. Fixed(?) the title.

**Comment by pnadube** [comment]
needs to be rewritten.
