### ISSUE TITLE
18512 - Use Puma and Foreman to deploy Rails applications with zero downtime - ALL DISTROS

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#47]

**Comment by gnakan** [comment]
Two issues faced:  1.       We have written the common steps for the installation and configuration of Puma, Foreman and Capatrino using Ruby commands. However, we are facing issue in the config/puma.rb script. In this script, if we write "workers 2" at top of the script, it gives an error of production database. And if we comment that line, puma services execute successfully. But in that case, we cannot use the utilities of concurrent puma services for workers utilities.
 <code>
Script:
#config/puma.rb
threads 1, 6
workers 2 # if comment, run success
 
on_worker_boot do
  require "active_record"
  cwd = File.dirname(__FILE__)+"/.."
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(ENV["DATABASE_URL"] || YAML.load_file("#{cwd}/config/database.yml")[ENV["RAILS_ENV"]])
end
 
Error :  `resolve_symbol_connection': 'production' database is not configured. Available: [] (ActiveRecord::AdapterNotSpecified)
 
 
2.       Another issue that we face is in the Capatrino deployment script. In this we get error of undefined method map:
 
Error:
NoMethodError: undefined method `map' for :roles:Symbol
 
Script :
Tasks: TOP => production
(See full trace by running task with --trace)
 
# config/deploy.rb
set :app_name, "puma-test-app"
set :user, "puma-test-user"
 
namespace :foreman do
  desc "Export the Procfile to Ubuntu's upstart scripts"
  task :export, :roles => :app do
    run "cd #{current_path} && #{sudo} foreman export upstart /etc/init -a #{app_name} -u #{user} -l /var/#{app_name}/log"
  end
 
  desc "Start the application services"
  task :start, :roles => :app do
    run "#{sudo} service #{app_name} start"
  end
 
  desc "Stop the application services"
  task :stop, :roles => :app do
    run "#{sudo} service #{app_name} stop"
  end
 
  desc "Restart the application services"
  task :restart, :roles => :app do
    run "#{sudo} service #{app_name} start || #{sudo} service #{app_name} restart"
  end
end
 </code>
If we remove the “roles” in the above script, it keeps on executing the 'cap production deploy' in a continuous loop.

**Comment by gnakan** [comment]
What about the accepted answer here: http://stackoverflow.com/questions/27657870/whenever-cron-job-in-rails-fails-with-production-database-is-not-configured-er

**Comment by gnakan** [comment]
We had already followed the stackoverflow link for this issue.
 
The issue is with the worker label in puma.rb. If we add this worker, error occurs, otherwise the Rails application runs smoothly.

**Comment by garynakanelua** [comment]
@advaiya-main : Wanted to see if you seen the comment above and if this is still blocked?

**Comment by advaiya-main** [comment]
@gnakan: Hi Gary, this is still an issue and is in blocked state.
