### ISSUE TITLE
00050 - Set Up WordPress Domain Mapping in Apache - Debian

### ISSUE THREAD

**Issue by kharise** [gnakan/gd-cloud-docs#524]

**Comment by kharise** [comment]
Forked from 00047

**Comment by susankayjordan** [comment]
No Code (Article)

**Comment by garynakanelua** [comment]
@kharise: I don't currently see this article in repo. Did you add an initial version?

**Comment by kharise** [comment]
@garynakanelua: I collapsed this into 00047 (Ub/Deb). So we'll close this one then? Sorry for the confusion!
