### ISSUE TITLE
00074 - Install CouchDB From Source - Fedora

### ISSUE THREAD

**Issue by kharise** [gnakan/gd-cloud-docs#570]
Forked from 00072 as a result of testing. Needs to be written to Fedora.

**Comment by kharise** [comment]
@advaiya-main Forked from 00072. I've pasted in the text from 00072 and changed references to Centos to Fedora but otherwise it's the same article. Please write for Fedora and validate. I'll test once done.

**Comment by advaiya-main** [comment]
@gnakan: Hi Gary, when installing couchDB package from source, we are getting the following error:

cc1: all warnings being treated as errors
Makefile:669: recipe for target 'couch_js/couchjs-http.o' failed
make[5]: *** [couch_js/couchjs-http.o] Error 1
make[5]: Leaving directory '/home/vikaskhowar04/apache-couchdb-1.6.1/src/couchdb
Makefile:397: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/vikaskhowar04/apache-couchdb-1.6.1/src/couchdb
Makefile:541: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/vikaskhowar04/apache-couchdb-1.6.1/src/couchdb
Makefile:687: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/vikaskhowar04/apache-couchdb-1.6.1/src'
Makefile:481: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vikaskhowar04/apache-couchdb-1.6.1'
Makefile:381: recipe for target 'all' failed
make: *** [all] Error 2

Please suggest.
