### ISSUE TITLE
17418 - Deploy Django with PostgreSQL, NGINX, and Gunicorn - CentOS 6

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#60]
https://docs.google.com/document/d/1a3211of6NUL7r3MRQhH98LyUBuPIA2MwqiRbgl3fENY/edit?usp=sharing

**Comment by susankayjordan** [comment]
Validated Coded, @CrystalSmithwick  I think the time may be a bit short.

**Comment by CrystalSmithwick** [comment]
Started, but putting aside for a shorter article.

**Comment by CrystalSmithwick** [comment]
Edited.  This was a messy one.  Tester, please tag any variables that I missed.  Good luck!

**Comment by pnadube** [comment]
python2.7 -V 
Command not found.

**Comment by gnakan** [comment]
@pnadube: Updated the python command in the article

**Comment by pnadube** [comment]
gunicorn django_dev.wsgi:application --bind django_dev.com:8000 fails. Fixed a few things before this. 
Error-  No module named django_dev.wsgi among other errors
