### ISSUE TITLE
18269 - Install and configure Django CMS - Arch Linux

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#61]
Reference: https://www.digitalocean.com/community/tutorials/how-to-set-up-and-install-django-cms-on-a-debian-7-or-ubuntu-13-vps

**Comment by CrystalSmithwick** [comment]
The sibling articles were both at 85% match in copyscape.  I was able to edit 18268 down to 45% and move it to testing.  18267 was moved to "Ready for Drafting" with the label "Very technical accuracy."
