### ISSUE TITLE
18267 - Install and configure Django CMS - CentOS, Fedora

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#62]
Reference: https://www.digitalocean.com/community/tutorials/how-to-set-up-and-install-django-cms-on-a-debian-7-or-ubuntu-13-vps

**Comment by susankayjordan** [comment]
@Conrad 18267 - Install and configure Django CMS - CentOS, Fedora.html   has been coded

**Comment by CrystalSmithwick** [comment]
This is a long article with a lot of structure issues.

**Comment by CrystalSmithwick** [comment]
Returning to Conrad to add steps (or indicate to Susan where steps should go.)
Please make procedures into steps and move some of the informational text into an introduction for the appropriate section.   Feel free to schedule time to discuss.

**Comment by cjamesbpcs** [comment]
I have emailed the updated HTML code to Susan for code Validation.

**Comment by CrystalSmithwick** [comment]
Same issue as 18268.  Ran copyscape.  87% match with a DO article.  No edits made. I'm putting it aside and adding verify technical accuracy label.

**Comment by CrystalSmithwick** [comment]
Made major edits to 18268, which could be applied to his article too.  I got 18268 down to 45%, with no chunks of text more than a few words.   Per Gary, moved this to Drafting and added verify technical accuracy.
