### ISSUE TITLE
18268 - Install and configure Django CMS - Ubuntu, Debian

### ISSUE THREAD

**Issue by gnakan** [gnakan/gd-cloud-docs#63]
Reference: https://www.digitalocean.com/community/tutorials/how-to-set-up-and-install-django-cms-on-a-debian-7-or-ubuntu-13-vps

**Comment by susankayjordan** [comment]
Validated code no changes made to file

**Comment by susankayjordan** [comment]
closed by Mistake

**Comment by CrystalSmithwick** [comment]
Not found in repos.  BLOCKED.  Back to Code.

**Comment by susankayjordan** [comment]
Had to rebuild the entire file  but it is there now

**Comment by CrystalSmithwick** [comment]
Started edits.

**Comment by CrystalSmithwick** [comment]
Major edits. Got the copyscape down to 45%.  Sending for testing.   

Same edits could be applied to 18269 and 18267.

**Comment by CrystalSmithwick** [comment]
Tester, if you can think of anyway to make the code samples more unique, please do.  Also check for variables. I admit I was a bit cross eyed at the end of this one.  Ask Gary or Susan, if you have questions.
